### ISSUE TITLE
Unrecognised **commodities**

### ISSUE THREAD

**Issue by natblundell** [jtickle/Picard#15]
More bad news...

usscargoancientartefact
usscargorareartwork
usscargorebeltransmissions
usscargotechnicalblueprints
wreckagecomponents
esusekucaviar

All unrecognised. These are all commodities, but picard is still trying to sync them.

**Comment by nordicpc** [comment]
Thanks for the list Nat! I think Jeff's going to get a point release with an updated list soon.

Since Inara does pay attention to some commodities, the software can't just get rid of all commodities. So there is a list of irrelevant ones that we've been adding to as they come up.

I personally have downloaded the project, and will sometimes add the names into EliteInaraLookups.txt and then do a debug build to get past it until a new point release comes up. It will still run just fine, and once Jeff gets a new MSI built, you can upgrade and get back on the release branch.

Cheers!
