### ISSUE TITLE
Missing a couple things

### ISSUE THREAD

**Issue by nordicpc** [jtickle/Picard#3]
I did a couple of hours of engineering last night, and when I ran Pickard, I was missing one commodity (Energy Grid Assembly), and three datas (untypical shield assemblies). As best I can tell, here are the logs relevant:

EGA:
`Journal.161230183927.01.log:{ "timestamp":"2016-12-31T02:04:11Z", "event":"MarketBuy", "Type":"powergridassembly", "Count":3, "BuyPrice":1583, "TotalCost":4749 }
Journal.161230183927.01.log:{ "timestamp":"2016-12-31T02:32:41Z", "event":"EngineerCraft", "Engineer":"Elvira Martuuk", "Blueprint":"FSD_LongRange", "Level":4, "Ingredients":{"powergridassembly":1, "manganese":1, "chemicaldistillery":1, "hyperspacetrajectories":1 } }
Journal.161230183927.01.log:{ "timestamp":"2016-12-31T02:33:26Z", "event":"EngineerCraft", "Engineer":"Elvira Martuuk", "Blueprint":"FSD_LongRange", "Level":4, "Ingredients":{"powergridassembly":1, "manganese":1, "chemicaldistillery":1, "hyperspacetrajectories":1 } }`

USA:
`Journal.161230183927.01.log:{ "timestamp":"2016-12-31T01:14:43Z", "event":"MaterialCollected", "Category":"Encoded", "Name":"shielddensityreports", "Count":3 }`

I have no idea how it could have missed the marketbuy, but it wasn't showing any negatives. Also, wasn't showing any unknown debugs. All in all, it picked off -8 materials, 29 datas, and -2 commodities from various activities, so pretty darn good. And I love the new coloring and totals!!!

**Comment by jtickle** [comment]
It now won't let you post to Inara if those materials are wrong.  But it will now count the unknowns instead of not counting them :-)  Also, it will show you them in a box, so you shouldn't have to dig through your log files unless it's a really really messed up name.

I have had to add the ability to "ignore unrelated commodities" although I didn't work too hard on it because they're taking that out.  In fact, it might be a good idea to just release this like the day after they release that update, since the existence of commodities has been every damn problem with this program.

If you are getting a bunch of commodities that are not related to Engineering, it is now very easy to ignore them.  After you get the "unrecognized materials" popup, open EliteLogs.cs and paste the clipboard around line 80 where all the IgnoreCommodities are.  Recompile, and issue a pull request so I get a copy too.

Still send me the wrong comm/mat/data that ARE related to Engineering, or fix them just below the IgnoreCommodities list in EliteLogs.cs.  Friendly reminder that the "localised" names with capitals and spaces ARE CORRECT; what needs to be changed are the lowercased and messy names on the left.  If you get a "localised" looking name that is in the unknown things list, you probably just need to ignore it like above.

**Comment by nordicpc** [comment]
Cool, I’ll check this out in the evening and see if it fixes it.

**Comment by nordicpc** [comment]
YAY! It works!


I totally agree on holding out until this new update it out. 2.2.03 beta 4 has been sitting there for a couple weeks now, and it's supposed to launch soon, so it will probably be soon. There might be one more beta, but it will probably be a small one.


Cheers man!


-Nate

________________________________
From: Nate Solberg
Sent: Tuesday, January 3, 2017 1:01:14 PM
To: jtickle/Picard; jtickle/Picard
Cc: Author
Subject: RE: [jtickle/Picard] Missing a couple things (#3)

Cool, I'll check this out in the evening and see if it fixes it.
